layout_spectrum: 0.6491256
typography_spectrum: 0.4092222
color:
  saturation: 0.08130799
  lightness: 0.2557018
  brandStrength: 0.2580088
  rhythmicContrast: 0.6922553
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Cityscope.hu
